<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30219" started-at="2018-07-28T08:16:07Z" finished-at="2018-07-28T08:16:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="30219" started-at="2018-07-28T08:16:07Z" finished-at="2018-07-28T08:16:37Z">
      <class name="ExtentReportsDemo.FirstReport">
        <test-method status="PASS" signature="OpeningBroswer()[pri:0, instance:ExtentReportsDemo.FirstReport@a7b76d]" name="OpeningBroswer" is-config="true" duration-ms="23503" started-at="2018-07-28T08:16:07Z" finished-at="2018-07-28T08:16:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpeningBroswer -->
        <test-method status="FAIL" signature="Login()[pri:0, instance:ExtentReportsDemo.FirstReport@a7b76d]" name="Login" duration-ms="6549" started-at="2018-07-28T08:16:30Z" finished-at="2018-07-28T08:16:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [dshttps://www.facebook.com/login.php?login_attempt=1&lwv=110] but found [https://www.facebook.com/login.php?login_attempt=1&lwv=110]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [dshttps://www.facebook.com/login.php?login_attempt=1&lwv=110] but found [https://www.facebook.com/login.php?login_attempt=1&lwv=110]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at ExtentReportsDemo.FirstReport.Login(FirstReport.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:ExtentReportsDemo.FirstReport@a7b76d]" name="CloseBrowser" is-config="true" duration-ms="136" started-at="2018-07-28T08:16:37Z" finished-at="2018-07-28T08:16:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- ExtentReportsDemo.FirstReport -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
